# Generated by Django 6.0.2 on 2026-02-13 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Enrollment",
        ),
    ]
